### ISSUE TITLE
Usage in a bucklescript/js project?

### ISSUE THREAD

**Issue by idkjs** [shonfeder/emojitsu#2]
Any chance I can import this in a reasonml/rescript project and call the methods on some emoji string. I would love to be able to call find-name on a list of emojis.

Thank you for sharing.

**Comment by shonfeder** [comment]
Hi! I think you should be able to import and use the functions in https://github.com/shonfeder/emojitsu/blob/master/lib/github.ml 

I don’t use reasonml/rescript, so haven’t tried that use case myself. But if you hit any problems with that use case and I can help resolve them, let me know.

If it would help you to have this published on Opam, I should be able to make that happen too.

**Comment by idkjs** [comment]
@shonfeder thanks for getting back to me. 

I may not be explaining this correctly so let me tell you what i am trying to do and you can tell me if its possible. I am trying to recreate this type in ReasonML. https://github.com/makenotion/notion-sdk-js/blob/20a7ba7a61aeec1328b99f3497f0e67848de0532/src/api-endpoints.ts#L810 which is a variant.

Could I use this lib or some of your functions to do something like that?

Thank you, sir.

**Comment by shonfeder** [comment]
Sorry that replying to this question slipped thru my the crack in my task lists! I hope you have figured out how to solve your challenge by now. Please re-open the issue with up to date information if this questions is still relevant for your work. Thanks!
